# Generated by Django 4.0.2 on 2022-03-08 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaliable',
            new_name='is_available',
        ),
    ]
