# Generated by Django 4.0.2 on 2022-03-18 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='is_activate',
            new_name='is_active',
        ),
    ]
